## Numpy Lecture Notes from JosePortilla_UDEMY - Henric Jandoc

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [13]:
len(np.linspace(0,10,100))

100

In [14]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random Distributions

In [15]:
np.random.rand(3,3) # gives a random number between 0 and 1

array([[0.58151442, 0.9133523 , 0.74197713],
       [0.45627569, 0.01026316, 0.34674165],
       [0.42147451, 0.71529859, 0.76091121]])

In [16]:
np.random.randn(3,3) # returns from standard normal dist.

array([[-1.68509006,  1.66379369, -0.6810871 ],
       [ 0.26211598,  0.79629731, -1.79148294],
       [ 0.29750814,  1.45989078,  0.80545166]])

In [17]:
np.random.randint(0,10, size = 5)  # returns a random integer

array([2, 2, 5, 7, 9])

In [18]:
np.random.randint(0,10, size = (2,2))

array([[4, 8],
       [1, 4]])

In [19]:
np.random.seed(25)
np.random.rand(2,2)

array([[0.87012414, 0.58227693],
       [0.27883894, 0.18591123]])

In [20]:
arr = np.arange(0,25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
randarr = np.random.randint(0,101,10)

In [24]:
randarr.max()

89

In [25]:
randarr.min()

1

In [26]:
randarr.mean()

36.3

In [27]:
randarr.std()

26.996481252192847

In [28]:
# the index of these

randarr.argmax()

5

In [29]:
randarr.argmin()

8

In [30]:
arr.shape

(25,)

## Indexing and Selection

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[8]

8

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[:5]

array([0, 1, 2, 3, 4])

In [37]:
arr[-1]

10

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[0:5] = 100  # broadcasting

In [40]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [41]:
arr = np.arange(0,11)

In [42]:
slice_of_arr = arr[0:5]

In [43]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [44]:
slice_of_arr[:] = 99

In [45]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [46]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [49]:
arr_2d[0]

array([ 5, 10, 15])

In [50]:
arr_2d[1]

array([20, 25, 30])

In [51]:
arr_2d[0,0]

5

In [52]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

In [60]:
arr = np.arange(1,11)

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
arr < 4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [61]:
arr == 0

array([False, False, False, False, False, False, False, False, False,
       False])

In [62]:
bool_arr = arr>4

In [63]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[arr<3]

array([1, 2])

## Numpy Operations

In [66]:
arr = np.arange(0,10)

In [67]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
# arr * arr - arr / arr

In [72]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
# np.log(arr)

In [77]:
# just look up the documentation

In [78]:
arr.sum()

45

In [79]:
arr.mean()

4.5

In [80]:
arr.max()

9

In [81]:
arr.var()

8.25

In [82]:
arr.std()

2.8722813232690143

In [84]:
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [85]:
arr2d.sum()

45

In [86]:
arr2d.sum(axis = 0)

array([12, 15, 18])

In [87]:
arr2d.sum(axis = 1)

array([ 6, 15, 24])